# Generated by Django 4.2.7 on 2026-03-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('completed_attempts', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('lowest_score', models.FloatField(default=0.0)),
                ('average_time_seconds', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='quizzes.quiz')),
            ],
            options={
                'verbose_name_plural': 'Quiz Analytics',
                'db_table': 'quiz_analytics',
            },
        ),
    ]
